In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

#df = pd.DataFrame(data=pd.read_csv('drive/MyDrive/Colab Notebooks/nlp/nlp_datasets/Covid_Data.csv'))  # https://www.kaggle.com/datasets/meirnizri/covid19-dataset
df = pd.read_csv(r"C:\Users\Darya\Covid Data.csv")
df = df.dropna()
df = df.drop(columns='DATE_DIED')
# df["CLASIFFICATION_FINAL"] = df["CLASIFFICATION_FINAL"].replace([[1,2,3],[4,5,6,7]], [1, 0])

df

USMER  MEDICAL_UNIT  SEX  PATIENT_TYPE  INTUBED  PNEUMONIA  AGE  \
0            2             1    1             1       97          1   65   
1            2             1    2             1       97          1   72   
2            2             1    2             2        1          2   55   
3            2             1    1             1       97          2   53   
4            2             1    2             1       97          2   68   
...        ...           ...  ...           ...      ...        ...  ...   
1048570      2            13    2             1       97          2   40   
1048571      1            13    2             2        2          2   51   
1048572      2            13    2             1       97          2   55   
1048573      2            13    2             1       97          2   28   
1048574      2            13    2             1       97          2   52   

         PREGNANT  DIABETES  COPD  ASTHMA  INMSUPR  HIPERTENSION  \
0               2         2     2       2        2             1   
1              97         2     2       2        2             1   
2              97         1     2       2        2             2   
3               2         2     2       2        2             2   
4              97         1     2       2        2             1   
...           ...       ...   ...     ...      ...           ...   
1048570        97         2     2       2        2             2   
1048571        97         2     2       2        2             1   
1048572        97         2     2       2        2             2   
1048573        97         2     2       2        2             2   
1048574        97         2     2       2        2             2   

         OTHER_DISEASE  CARDIOVASCULAR  OBESITY  RENAL_CHRONIC  TOBACCO  \
0                    2               2        2              2        2   
1                    2               2        1              1        2   
2                    2               2        2              2        2   
3                    2               2        2              2        2   
4                    2               2        2              2        2   
...                ...             ...      ...            ...      ...   
1048570              2               2        2              2        2   
1048571              2               2        2              2        2   
1048572              2               2        2              2        2   
1048573              2               2        2              2        2   
1048574              2               2        2              2        2   

         CLASIFFICATION_FINAL  ICU  
0                           3   97  
1                           5   97  
2                           3    2  
3                           7   97  
4                           3   97  
...                       ...  ...  
1048570                     7   97  
1048571                     7    2  
1048572                     7   97  
1048573                     7   97  
1048574                     7   97  

[1048575 rows x 20 columns]

In [2]:
print(df['CLASIFFICATION_FINAL'].value_counts())

7    499250
3    381527
6    128133
5     26091
1      8601
4      3122
2      1851
Name: CLASIFFICATION_FINAL, dtype: int64


In [3]:
X, y = df.drop(columns='CLASIFFICATION_FINAL'), df['CLASIFFICATION_FINAL']

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=0)

In [5]:
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

clf = SGDClassifier()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
clf.score(X_test, y_test)

0.5098768493263907

In [15]:
print(confusion_matrix(y_test, y_pred, labels=[1, 0]))
print("Accuracy: ", accuracy_score(y_test, y_pred) )
print("Precision: ", precision_score(y_test, y_pred, average = 'weighted') )
print("Recall: ", recall_score(y_test, y_pred, average = 'weighted') )
print("f1-score: ", f1_score(y_test, y_pred,average = 'weighted') )

[[0 0]
 [0 0]]
Accuracy:  0.5098768493263907
Precision:  0.5015421050998093
Recall:  0.5098768493263907
f1-score:  0.4707403774650173


C:\Games\conda\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [25]:
from sklearn.ensemble import RandomForestClassifier

clf2 = RandomForestClassifier(max_depth=2, random_state=15122022)
clf2.fit(X_train, y_train)
y_pred2 = clf2.predict(X_test)
clf2.score(X_test, y_test)

0.5254216813849841

In [26]:
print(confusion_matrix(y_test, y_pred2, labels=[1, 0]))
print("Accuracy: ", accuracy_score(y_test, y_pred2) )
print("Precision: ", precision_score(y_test, y_pred2, average = 'weighted') )
print("Recall: ", recall_score(y_test, y_pred2, average = 'weighted') )
print("f1-score: ", f1_score(y_test, y_pred2,average = 'weighted') )

[[0 0]
 [0 0]]
Accuracy:  0.5254216813849841
Precision:  0.4514962567718982
Recall:  0.5254216813849841
f1-score:  0.4487178552365369


C:\Games\conda\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [27]:
clf3 = LogisticRegression(random_state=0).fit(X_train, y_train)
clf3.score(X_train, y_train)

C:\Games\conda\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.5311751083824757

In [28]:
y_pred3 = clf3.predict(X_test)
clf3.score(X_test, y_test)

0.5333752948431848

In [29]:
print(confusion_matrix(y_test, y_pred3, labels=[1, 0]))
print("Accuracy: ", accuracy_score(y_test, y_pred3) )
print("Precision: ", precision_score(y_test, y_pred3, average = 'weighted') )
print("Recall: ", recall_score(y_test, y_pred3, average = 'weighted') )
print("f1-score: ", f1_score(y_test, y_pred3,average = 'weighted') )

[[0 0]
 [0 0]]
Accuracy:  0.5333752948431848
Precision:  0.5235491531053093
Recall:  0.5333752948431848
f1-score:  0.47386730611972994


C:\Games\conda\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
